.TH TORRENT-SEARCH "1" "24 Августа 2010" "torrent-search 0.9.0" "Приложение"
.SH ИМЯ
torrent-search \- страница справки для torrent-search 0.9.0
.SH КРАТКИЙ ОБЗОР
.B torrent-search
[\fIoptions\fR]
.SH БАЗОВЫЕ ОПЦИИ
.TP
\fB\-h\fR, \fB\-\-help\fR
Показать эту справку и выйти
.TP
\fB\-v\fR, \fB\-\-version\fR
Показать номер версии и выйти
.TP
\fB\-s\fR, \fB\-\-search\fR
Запустить поиск при запуске
.TP
\fB\-\-no\-plugins\-check\fR
Не проверять обновления дополнений
.SH ДОПОЛНИТЕЛЬНЫЕ ОПЦИИ (ДЛЯ РАЗРАБОТЧИКОВ)
.TP
\fB\-\-share\-dir\fR
Путь к общей папке (по умолчанию: /usr/share)
.TP
\fB\-\-add\-plugin\fR
Добавить дополнение из другого каталога
.SH АВТОР
Gwendal Le Bihan (gwendal.lebihan.dev@gmail.com)
