.TH TORRENT-SEARCH "1" "21 Janvier 2012" "torrent-search 0.11.2" "Application"
.SH NOM
torrent-search \- page de manuel pour torrent-search 0.11.2
.SH SYNOPSIS
.B torrent-search
[\fIoptions\fR]
.SH OPTIONS BASIQUES
.TP
\fB\-h\fR, \fB\-\-help\fR
Afficher ce message d'aide et quitter
.TP
\fB\-v\fR, \fB\-\-version\fR
Afficher le numéro de version et quitter
.TP
\fB\-s\fR, \fB\-\-search\fR
Effectuer une recherche au démarrage
.TP
\fB\-\-no\-plugins\-check\fR
Ne pas chercher les mises à jour de plugins
.SH OPTIONS AVANCéES (POUR LES DéVELOPPEURS)
.TP
\fB\-\-share\-dir\fR
Chemin vers le répertoire share (défaut: /usr/share)
.TP
\fB\-\-add\-plugin\fR
Ajouter un plugin à partir d'un chemin personnalisé
.SH AUTEUR
Gwendal Le Bihan (gwendal.lebihan.dev@gmail.com)