.TH TORRENT-SEARCH "1" "24 Augustus 2010" "torrent-search 0.9.0" "Application"
.SH NAME
torrent-search \- help pagina voor torrent-search 0.9.0
.SH SYNOPSIS
.B torrent-search
[\fIoptions\fR]
.SH BASIS OPTIES
.TP
\fB\-h\fR, \fB\-\-help\fR
Laat deze help-pagina zien en sluit af
.TP
\fB\-v\fR, \fB\-\-version\fR
Laat versienummer zien en sluit af
.TP
\fB\-s\fR, \fB\-\-search\fR
Zoek bij het opstarten
.TP
\fB\-\-no\-plugins\-check\fR
Controleer niet op updates
.SH GEAVANCEERDE OPTIES (VOOR ONTWIKKELAARS)
.TP
\fB\-\-share\-dir\fR
Pad naar share-map (default: /usr/share)
.TP
\fB\-\-add\-plugin\fR
Voeg een plugin toe vanaf de harde schijf
.SH AUTHOR
Gwendal Le Bihan (gwendal.lebihan.dev@gmail.com)
